import {
  PyramidMesh,
  TempleMesh,
  ObeliskMesh,
  ColumnMesh,
  StatueMesh,
  PalmTreeMesh,
  DesertDuneMesh,
  StoneWallMesh,
  HieroglyphicPanelMesh,
  TorchMesh,
  AncientDoorMesh,
  SpaceshipMesh,
  SpaceStationMesh,
  PlanetMesh,
  AsteroidMesh,
  LanderMesh,
  TreeMesh,
  CoralMesh,
  HabitatMesh,
  RuinsMesh,
  CastleTowerMesh,
  CrateMesh,
  ConsoleMesh,
  RockMesh,
  BoxMesh,
  SphereMesh,
} from './meshes.jsx'
import { FishMesh, JellyfishMesh, SeaweedMesh, FlowerMesh, BirdMesh } from './lifeMeshes.jsx'
import { GenericProceduralMesh } from './genericMesh.jsx'

export const GENERATORS = {
  pyramid: PyramidMesh,
  temple: TempleMesh,
  obelisk: ObeliskMesh,
  column: ColumnMesh,
  statue: StatueMesh,
  palm_tree: PalmTreeMesh,
  desert_dune: DesertDuneMesh,
  stone_wall: StoneWallMesh,
  hieroglyphic_panel: HieroglyphicPanelMesh,
  torch: TorchMesh,
  ancient_door: AncientDoorMesh,
  spaceship: SpaceshipMesh,
  space_station: SpaceStationMesh,
  planet: PlanetMesh,
  asteroid: AsteroidMesh,
  lander: LanderMesh,
  tree: TreeMesh,
  coral: CoralMesh,
  habitat: HabitatMesh,
  ruins: RuinsMesh,
  castle_tower: CastleTowerMesh,
  crate: CrateMesh,
  console: ConsoleMesh,
  rock: RockMesh,
  fish: FishMesh,
  jellyfish: JellyfishMesh,
  seaweed: SeaweedMesh,
  flower: FlowerMesh,
  bird: BirdMesh,
  generic: GenericProceduralMesh,
  box: BoxMesh,
  sphere: SphereMesh,
}

export function getGenerator(type) {
  return GENERATORS[type] ?? BoxMesh
}
